name: Build and test ijson

# Build on every branch push, tag push, and pull request change:
on:
  push:
  pull_request:
  schedule:
  # 00:00 UTC every Saturday, don't bother anyone
  - cron: '0 0 * * 6'

jobs:

  fast_tests:
    name: Build ijson and run unit tests (${{ matrix.os }}, ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-12]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13-dev"]
        include:
          - os: ubuntu-latest
            python_version: "pypy3.9"
          - os: ubuntu-latest
            python_version: "pypy3.10"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install build test dependencies
        run: pip install setuptools

      - name: Install Yajl
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libyajl-dev

      - name: Build ijson
        env:
          IJSON_EMBED_YAJL: ${{ matrix.os != 'ubuntu-latest' && '1' || '0' }}
        run: python setup.py develop

      - name: Install test dependencies
        env:
          CFFI_DEPENDENCY: ${{ matrix.python_version == '3.13-dev' && 'cffi==1.17.0rc1' || 'cffi' }}
        run: pip install pytest $CFFI_DEPENDENCY

      - name: Run unittests
        run: pytest -vv

      - name: Run doctests
        run: pytest --doctest-modules --doctest-ignore-import-errors src
